using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using DigitoyEngine;

namespace DigitoyEditor;

// Reflection'la kurulmus CANLI TypeCatalog'u C# kaynagina serilestirir. Kural
// motoru TEK (SerializedType.Build / ComputeFlags / importer kayitlari) — yazici
// sadece SONUCU koda doker, semantik ikinci kez yazilmaz (Roslyn generator'a
// karsi bilincli tercih). Ayni cikti: editorde in-memory derlenip canli katalog
// olur (RegistryCompiler), player export'unda diske .cs yazilip normal derlenir.
// Erisilemeyen tipler (private nested, generic) RegisterReflective fallback'ine
// duser. Private [SerializeField] alanlar [UnsafeAccessor] thunk'lariyla okunur
// (visibility bypass, AOT uyumlu, alan erisimi hizinda).
public static class CatalogWriter
{
    // Uretilen assembly adi (engine/game InternalsVisibleTo bununla eslesir).
    public const string AssemblyName = "Digitoy.Registry";

    public static string Write(TypeCatalog cat, Func<Type, bool> include)
    {
        var entries = new List<TypeCatalog.Entry>();
        foreach (var e in cat.Entries)
            if (include(e.Type))
                entries.Add(e);
        entries.Sort((a, b) => string.CompareOrdinal(a.Type.FullName, b.Type.FullName));

        var sb = new StringBuilder(64 * 1024);
        sb.Append("// <auto-generated/> CatalogWriter ciktisi — ELLE DUZENLEME.\n");
        sb.Append("namespace DigitoyEngine.Generated;\n\n");
        sb.Append("public static class Registry\n{\n");
        sb.Append("    public static global::DigitoyEngine.TypeCatalog Build()\n");
        sb.Append("    {\n        var cat = new global::DigitoyEngine.TypeCatalog();\n        RegisterAll(cat);\n        return cat;\n    }\n\n");

        var body = new StringBuilder(8 * 1024);   // Reg_i metodlari + thunk'lar
        var calls = new StringBuilder(1024);      // RegisterAll govdesi

        for (int i = 0; i < entries.Count; i++)
        {
            var e = entries[i];
            if (CanEmit(e))
            {
                calls.Append("        Reg_").Append(i).Append("(cat);\n");
                EmitEntry(body, e, i);
            }
            else
            {
                // private nested / generic tanim: ayni assembly'den reflection kaydi.
                calls.Append("        cat.RegisterReflective(global::System.Type.GetType(")
                     .Append(Quote(e.Type.FullName + ", " + e.Type.Assembly.GetName().Name))
                     .Append(", throwOnError: true));\n");
            }
        }
        foreach (var kv in cat.Aliases)
            calls.Append("        cat.RegisterAlias(").Append(Quote(kv.Key)).Append(", ").Append(Quote(kv.Value)).Append(");\n");

        sb.Append("    public static void RegisterAll(global::DigitoyEngine.TypeCatalog cat)\n    {\n");
        sb.Append(calls);
        sb.Append("    }\n\n");
        sb.Append(body);
        sb.Append("}\n");
        return sb.ToString();
    }

    // --- tek entry emisyonu ---

    static void EmitEntry(StringBuilder sb, TypeCatalog.Entry e, int idx)
    {
        string tn = CsName(e.Type);
        var thunks = new StringBuilder();
        int thunkN = 0;

        sb.Append("    static void Reg_").Append(idx).Append("(global::DigitoyEngine.TypeCatalog cat)\n    {\n");

        // Sema (nested diziler once, referans siralamasi icin).
        EmitSchemaArray(sb, e.Schema, "s", e, idx, thunks, ref thunkN);

        sb.Append("        cat.Register(new global::DigitoyEngine.TypeCatalog.Entry\n        {\n");
        sb.Append("            Type = typeof(").Append(tn).Append("),\n");
        sb.Append("            Name = ").Append(Quote(e.Name)).Append(",\n");
        sb.Append("            Create = ").Append(CreateExpr(e.Type, tn)).Append(",\n");
        sb.Append("            CopyTo = ").Append(CopyToExpr(e.Type, tn, idx, thunks, ref thunkN)).Append(",\n");
        sb.Append("            Flags = (global::DigitoyEngine.LifecycleFlags)").Append((ushort)e.Flags).Append(",\n");
        sb.Append("            Schema = s,\n");
        sb.Append("            Previewable = ").Append(e.Previewable ? "true" : "false").Append(",\n");
        sb.Append("        });\n    }\n\n");
        sb.Append(thunks);
    }

    static string CreateExpr(Type t, string tn)
    {
        var ci = t.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
        if (ci != null && (ci.IsPublic || ci.IsAssembly || ci.IsFamilyOrAssembly))
            return "() => new " + tn + "()";
        // private/protected ctor: reflection fallback'iyle ayni davranis
        return "() => (global::DigitoyEngine.Component)global::System.Activator.CreateInstance(typeof(" + tn + "), nonPublic: true)";
    }

    static string CopyToExpr(Type t, string tn, int idx, StringBuilder thunks, ref int thunkN)
    {
        // RegisterReflective ile birebir alan kumesi: public VEYA [SerializeField].
        var sb = new StringBuilder();
        sb.Append("(s0, d0) =>\n            {\n");
        sb.Append("                var s1 = (").Append(tn).Append(")s0; var d1 = (").Append(tn).Append(")d0;\n");
        foreach (var fi in t.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (fi.IsLiteral)
                continue;
            if (!fi.IsPublic && !fi.IsDefined(typeof(SerializeFieldAttribute), false))
                continue;
            if (fi.IsPublic && !fi.IsInitOnly)
            {
                sb.Append("                d1.").Append(fi.Name).Append(" = s1.").Append(fi.Name).Append(";\n");
            }
            else
            {
                string th = EmitFieldThunk(thunks, fi, idx, ref thunkN);
                sb.Append("                ").Append(th).Append("(d1) = ").Append(th).Append("(s1);\n");
            }
        }
        sb.Append("            }");
        return sb.ToString();
    }

    // [UnsafeAccessor] ref-thunk: private/readonly alan erisimi (gorunurluk bypass).
    // Struct sahibi: ref parametre (boxed kopyaya degil box'in icine yazilir).
    static string EmitFieldThunk(StringBuilder thunks, FieldInfo fi, int idx, ref int thunkN)
    {
        string name = "F" + idx + "_" + thunkN++;
        thunks.Append("    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = ")
              .Append(Quote(fi.Name)).Append(")]\n");
        thunks.Append("    static extern ref ").Append(CsName(fi.FieldType)).Append(' ').Append(name)
              .Append('(').Append(fi.DeclaringType.IsValueType ? "ref " : "").Append(CsName(fi.DeclaringType)).Append(" o);\n\n");
        return name;
    }

    // Sema dizisi (nested Object/List-of-Object icin ozyinelemeli alt diziler).
    static void EmitSchemaArray(StringBuilder sb, SerializedType.FieldSchema[] schema, string var,
        TypeCatalog.Entry owner, int idx, StringBuilder thunks, ref int thunkN)
    {
        // Once alt diziler (degisken bildirimi kullanim oncesi olsun).
        for (int i = 0; i < schema.Length; i++)
            if (schema[i].Nested != null)
                EmitSchemaArray(sb, schema[i].Nested, var + "_" + i, null, idx, thunks, ref thunkN);

        sb.Append("        var ").Append(var).Append(" = new global::DigitoyEngine.SerializedType.FieldSchema[").Append(schema.Length).Append("];\n");
        for (int i = 0; i < schema.Length; i++)
        {
            var f = schema[i];
            sb.Append("        ").Append(var).Append('[').Append(i).Append("] = new global::DigitoyEngine.SerializedType.FieldSchema\n        {\n");
            sb.Append("            Name = ").Append(Quote(f.Name)).Append(",\n");
            if (f.FormerName != null)
                sb.Append("            FormerName = ").Append(Quote(f.FormerName)).Append(",\n");
            sb.Append("            Kind = ").Append(KindExpr(f.Kind)).Append(",\n");
            if (f.Kind == SerializedType.Kind.List)
                sb.Append("            ElementKind = ").Append(KindExpr(f.ElementKind)).Append(",\n");
            if (f.ElementType != null)
                sb.Append("            ElementType = typeof(").Append(CsName(f.ElementType)).Append("),\n");
            if (f.Nested != null)
                sb.Append("            Nested = ").Append(var).Append('_').Append(i).Append(",\n");
            sb.Append("            FieldType = typeof(").Append(CsName(f.Info.FieldType)).Append("),\n");
            sb.Append("            DeclaringType = typeof(").Append(CsName(f.Info.DeclaringType)).Append("),\n");
            EmitBoxedAccessors(sb, f, idx, thunks, ref thunkN);
            EmitContainerCtors(sb, f);

            // Tween/inspector sicak yolu: yalniz ust duzey component alanlari
            // (EnsureFloatAccessors ile ayni kapsam; nested'ta cast gecersiz).
            if (owner != null && (f.Kind == SerializedType.Kind.Float || f.Kind == SerializedType.Kind.Int))
                EmitFloatAccessors(sb, f, owner, idx, thunks, ref thunkN);

            sb.Append("        };\n");
        }
        // ShowIf: cozulmus kardes referanslari indeksle geri baglanir.
        for (int i = 0; i < schema.Length; i++)
        {
            var f = schema[i];
            if (f.ShowIf == null)
                continue;
            int j = Array.IndexOf(schema, f.ShowIf);
            if (j < 0)
                continue;
            sb.Append("        ").Append(var).Append('[').Append(i).Append("].ShowIf = ").Append(var).Append('[').Append(j).Append("];\n");
            if (f.ShowIfScalar != null)
                sb.Append("        ").Append(var).Append('[').Append(i).Append("].ShowIfScalar = ").Append(Quote(f.ShowIfScalar)).Append(";\n");
        }
    }

    // Boxed Get/Set: release serializer/clone yolunun tek erisim kapisi.
    // Struct sahibi: Set box'in icine Unsafe.Unbox ref'iyle yazar (kopyaya degil).
    static void EmitBoxedAccessors(StringBuilder sb, SerializedType.FieldSchema f,
        int idx, StringBuilder thunks, ref int thunkN)
    {
        var fi = f.Info;
        string decl = CsName(fi.DeclaringType);
        string ft = CsName(fi.FieldType);
        bool structOwner = fi.DeclaringType.IsValueType;
        string unbox = "global::System.Runtime.CompilerServices.Unsafe.Unbox<" + decl + ">(o)";
        string getAccess, setAccess;
        if (fi.IsPublic && !fi.IsInitOnly)
        {
            getAccess = "((" + decl + ")o)." + fi.Name;
            setAccess = structOwner ? unbox + "." + fi.Name : getAccess;
        }
        else
        {
            string th = EmitFieldThunk(thunks, fi, idx, ref thunkN);
            getAccess = setAccess = th + "(" + (structOwner ? "ref " + unbox : "(" + decl + ")o") + ")";
        }
        sb.Append("            Get = o => ").Append(getAccess).Append(",\n");
        sb.Append("            Set = (o, v) => ").Append(setAccess).Append(" = (").Append(ft).Append(")v,\n");
    }

    static void EmitContainerCtors(StringBuilder sb, SerializedType.FieldSchema f)
    {
        if (f.Kind == SerializedType.Kind.List)
        {
            string et = CsName(f.ElementType);
            if (f.Info.FieldType.IsArray)
                sb.Append("            NewArray = n => new ").Append(et).Append("[n],\n");
            else
                sb.Append("            NewList = () => new global::System.Collections.Generic.List<").Append(et).Append(">(),\n");
        }
        if (f.ElementType != null && (f.Kind == SerializedType.Kind.Object
            || f.ElementKind == SerializedType.Kind.Object || f.ElementType.IsValueType))
        {
            string et = CsName(f.ElementType);
            sb.Append("            NewElement = () => ")
              .Append(f.ElementType.IsValueType ? "(object)default(" + et + ")" : "new " + et + "()")
              .Append(",\n");
        }
    }

    static void EmitFloatAccessors(StringBuilder sb, SerializedType.FieldSchema f,
        TypeCatalog.Entry owner, int idx, StringBuilder thunks, ref int thunkN)
    {
        var fi = f.Info;
        string decl = CsName(fi.DeclaringType);
        bool isInt = f.Kind == SerializedType.Kind.Int;
        string access;
        if (fi.IsPublic && !fi.IsInitOnly)
        {
            access = "((" + decl + ")c)." + fi.Name;
        }
        else
        {
            string th = EmitFieldThunk(thunks, fi, idx, ref thunkN);
            access = th + "((" + decl + ")c)";
        }
        sb.Append("            GetFloat = c => ").Append(isInt ? "(float)" : "").Append(access).Append(",\n");
        sb.Append("            SetFloat = (c, v) => ").Append(access).Append(" = ").Append(isInt ? "(int)v" : "v").Append(",\n");
    }

    static string KindExpr(SerializedType.Kind k)
        => "global::DigitoyEngine.SerializedType.Kind." + k;

    // --- tip erisilebilirligi + C# adi ---

    // Uretilen kod ayri assembly'de (Digitoy.Registry): public/internal (IVT) gorunur,
    // private/protected nested gorunmez. Generic tanimlar kayit edilemez.
    static bool CanEmit(TypeCatalog.Entry e)
    {
        var t = e.Type;
        if (t.IsGenericTypeDefinition || t.ContainsGenericParameters)
            return false;
        if (!Accessible(t))
            return false;
        // Sema/copy'de adi gecen tum tipler de gorunur olmali (Set cast'i +
        // typeof(FieldType) her serilesen alanin tipini kodda adlandirir).
        foreach (var fi in t.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (fi.IsLiteral || (!fi.IsPublic && !fi.IsDefined(typeof(SerializeFieldAttribute), false)))
                continue;
            if (!Accessible(fi.DeclaringType) || !Accessible(fi.FieldType))
                return false;
        }
        return SchemaTypesAccessible(e.Schema);
    }

    static bool SchemaTypesAccessible(SerializedType.FieldSchema[] schema)
    {
        if (schema == null)
            return true;
        foreach (var f in schema)
        {
            if (!Accessible(f.Info.DeclaringType))
                return false;
            if (f.ElementType != null && !Accessible(f.ElementType))
                return false;
            if (f.Nested != null && !SchemaTypesAccessible(f.Nested))
                return false;
        }
        return true;
    }

    internal static bool Accessible(Type t)
    {
        if (t == null)
            return false;
        if (t.IsArray || t.IsByRef || t.IsPointer)
            return Accessible(t.GetElementType());
        if (t.IsGenericParameter)
            return false;
        if (t.IsGenericType)
            foreach (var a in t.GetGenericArguments())
                if (!Accessible(a))
                    return false;
        for (var x = t; x != null; x = x.DeclaringType)
        {
            if (x.IsNested)
            {
                if (x.IsNestedPrivate || x.IsNestedFamily || x.IsNestedFamANDAssem)
                    return false; // IVT private/protected'i acmaz
            }
            else
            {
                return true; // top-level: public veya internal (IVT ile gorunur)
            }
        }
        return true;
    }

    internal static string CsName(Type t)
    {
        if (t.IsArray)
            return CsName(t.GetElementType()) + "[]";
        var sb = new StringBuilder();
        BuildName(t, sb);
        return sb.ToString();
    }

    static void BuildName(Type t, StringBuilder sb)
    {
        if (t.DeclaringType != null)
        {
            BuildName(t.DeclaringType, sb);
            sb.Append('.');
        }
        else
        {
            sb.Append("global::");
            if (!string.IsNullOrEmpty(t.Namespace))
                sb.Append(t.Namespace).Append('.');
        }
        string n = t.Name;
        int tick = n.IndexOf('`');
        if (tick >= 0)
            n = n.Substring(0, tick);
        sb.Append(n);
        if (t.IsGenericType)
        {
            sb.Append('<');
            var args = t.GetGenericArguments();
            for (int i = 0; i < args.Length; i++)
            {
                if (i > 0)
                    sb.Append(", ");
                sb.Append(CsName(args[i]));
            }
            sb.Append('>');
        }
    }

    static string Quote(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        sb.Append('"');
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
