using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using DigitoyEngine;

namespace DigitoyEditor;

// Reflection'la kurulmus CANLI TypeCatalog'u C# kaynagina serilestirir. Kural
// motoru TEK (SerializedType.Build / ComputeFlags / importer kayitlari) — yazici
// sadece SONUCU koda doker, semantik ikinci kez yazilmaz (Roslyn generator'a
// karsi bilincli tercih). Ayni cikti: editorde in-memory derlenip canli katalog
// olur (RegistryCompiler), player export'unda diske .cs yazilip normal derlenir.
// Erisilemeyen tipler (private nested, generic) RegisterReflective fallback'ine
// duser. Private [SerializeField] alanlar [UnsafeAccessor] thunk'lariyla okunur
// (visibility bypass, AOT uyumlu, alan erisimi hizinda).
public static class CatalogWriter
{
    // Uretilen assembly adi (engine/game InternalsVisibleTo bununla eslesir).
    public const string AssemblyName = "Digitoy.Registry";

    public static string Write(TypeCatalog cat, Func<Type, bool> include, string ns = "DigitoyEngine.Generated")
    {
        var entries = new List<TypeCatalog.Entry>();
        foreach (var e in cat.Entries)
            if (include(e.Type))
                entries.Add(e);
        entries.Sort((a, b) => string.CompareOrdinal(a.Type.FullName, b.Type.FullName));

        var sb = new StringBuilder(64 * 1024);
        sb.Append("// <auto-generated/> CatalogWriter ciktisi — ELLE DUZENLEME.\n");
        sb.Append("namespace ").Append(ns).Append(";\n\n"); // modul: benzersiz ad alani (host'un Registry'siyle tip adi cakismasin)
        sb.Append("public static class Registry\n{\n");
        sb.Append("    public static global::DigitoyEngine.TypeCatalog Build()\n");
        sb.Append("    {\n        var cat = new global::DigitoyEngine.TypeCatalog();\n        RegisterAll(cat);\n        return cat;\n    }\n\n");

        var body = new StringBuilder(8 * 1024);   // Reg_i metodlari + thunk'lar
        var calls = new StringBuilder(1024);      // RegisterAll govdesi

        for (int i = 0; i < entries.Count; i++)
        {
            var e = entries[i];
            if (CanEmit(e))
            {
                calls.Append("        Reg_").Append(i).Append("(cat);\n");
                EmitEntry(body, e, i);
            }
            else
            {
                // private nested / generic tanim: ayni assembly'den reflection kaydi.
                calls.Append("        cat.RegisterReflective(global::System.Type.GetType(")
                     .Append(Quote(e.Type.FullName + ", " + e.Type.Assembly.GetName().Name))
                     .Append(", throwOnError: true));\n");
            }
        }
        foreach (var kv in cat.Aliases)
            calls.Append("        cat.RegisterAlias(").Append(Quote(kv.Key)).Append(", ").Append(Quote(kv.Value)).Append(");\n");

        sb.Append("    public static void RegisterAll(global::DigitoyEngine.TypeCatalog cat)\n    {\n");
        sb.Append(calls);
        sb.Append("    }\n\n");
        sb.Append(body);
        sb.Append("}\n");
        return sb.ToString();
    }

    // --- tek entry emisyonu ---

    static void EmitEntry(StringBuilder sb, TypeCatalog.Entry e, int idx)
    {
        string tn = CsName(e.Type);
        var thunks = new StringBuilder();
        int thunkN = 0;

        sb.Append("    static void Reg_").Append(idx).Append("(global::DigitoyEngine.TypeCatalog cat)\n    {\n");

        // Sema (nested diziler once, referans siralamasi icin).
        EmitSchemaArray(sb, e.Schema, "s", idx, thunks, ref thunkN);
        EmitAnimArray(sb, e, idx, thunks, ref thunkN);

        sb.Append("        cat.Register(new global::DigitoyEngine.TypeCatalog.Entry\n        {\n");
        sb.Append("            Type = typeof(").Append(tn).Append("),\n");
        sb.Append("            Name = ").Append(Quote(e.Name)).Append(",\n");
        sb.Append("            Create = ").Append(CreateExpr(e.Type, tn)).Append(",\n");
        sb.Append("            CopyTo = ").Append(CopyToExpr(e.Type, tn, idx, thunks, ref thunkN)).Append(",\n");
        sb.Append("            Flags = (global::DigitoyEngine.LifecycleFlags)").Append((ushort)e.Flags).Append(",\n");
        sb.Append("            Schema = s,\n");
        sb.Append("            Previewable = ").Append(e.Previewable ? "true" : "false").Append(",\n");
        sb.Append("            Anim = a,\n");
        sb.Append("            ReadBaked = Read_").Append(idx).Append(",\n");
        sb.Append("        });\n    }\n\n");
        EmitBakedReader(sb, e, idx, thunks, ref thunkN);
        sb.Append(thunks);
    }

    // --- pismis sahne okuyucusu: alan indeksi -> dogrudan tipli atama ---
    // SceneBinary.Reader bayt duzeniyle birebir (WriteValue ile ayna). Boxing, Unsafe,
    // FieldSchema.Get/Set YOK: release/AOT yukleme yolu yalniz bu kodu kosar.
    static void EmitBakedReader(StringBuilder sb, TypeCatalog.Entry e, int idx, StringBuilder thunks, ref int thunkN)
    {
        var nested = new StringBuilder();
        int nestedN = 0;
        sb.Append("    static void Read_").Append(idx).Append("(global::DigitoyEngine.Component o, global::DigitoyEngine.SceneBinary.Reader r)\n    {\n");
        sb.Append("        var c = (").Append(CsName(e.Type)).Append(")o;\n");
        EmitReadSwitch(sb, e.Schema, "c", false, idx, nested, ref nestedN, thunks, ref thunkN, 2);
        sb.Append("    }\n\n");
        sb.Append(nested);
    }

    // owner: sahip ifadesi (class: degisken; struct: ref parametre adi).
    static void EmitReadSwitch(StringBuilder sb, SerializedType.FieldSchema[] schema, string owner, bool ownerIsStruct,
        int idx, StringBuilder nested, ref int nestedN, StringBuilder thunks, ref int thunkN, int indent)
    {
        string pad = new string(' ', indent * 4);
        sb.Append(pad).Append("int n = r.U16();\n");
        sb.Append(pad).Append("for (int i = 0; i < n; i++)\n");
        sb.Append(pad).Append("{\n");
        sb.Append(pad).Append("    switch (r.U16())\n");
        sb.Append(pad).Append("    {\n");
        for (int k = 0; k < schema.Length; k++)
        {
            var f = schema[k];
            string lv = FieldLValue(f.Info, owner, ownerIsStruct, idx, thunks, ref thunkN);
            sb.Append(pad).Append("        case ").Append(k).Append(":\n");
            sb.Append(pad).Append("        {\n");
            EmitReadField(sb, f, lv, idx, nested, ref nestedN, thunks, ref thunkN, indent + 3);
            sb.Append(pad).Append("            break;\n");
            sb.Append(pad).Append("        }\n");
        }
        sb.Append(pad).Append("    }\n");
        sb.Append(pad).Append("}\n");
    }

    static void EmitReadField(StringBuilder sb, SerializedType.FieldSchema f, string lv,
        int idx, StringBuilder nested, ref int nestedN, StringBuilder thunks, ref int thunkN, int indent)
    {
        string pad = new string(' ', indent * 4);
        string ft = CsName(f.Info.FieldType);
        switch (f.Kind)
        {
            case SerializedType.Kind.GoRef:
                sb.Append(pad).Append("r.GoRef(v => ").Append(lv).Append(" = (").Append(ft).Append(")v);\n");
                break;
            case SerializedType.Kind.CompRef:
                sb.Append(pad).Append("r.CompRef(v => ").Append(lv).Append(" = (").Append(ft).Append(")v);\n");
                break;
            case SerializedType.Kind.Object:
                {
                    string rd = EmitNestedReader(f, idx, nested, ref nestedN, thunks, ref thunkN);
                    if (f.ElementType.IsValueType)
                        sb.Append(pad).Append("if (r.U8() != 0) ").Append(rd).Append("(ref ").Append(lv).Append(", r);\n");
                    else
                    {
                        sb.Append(pad).Append("if (r.U8() != 0)\n");
                        sb.Append(pad).Append("{\n");
                        sb.Append(pad).Append("    var o2 = ").Append(lv).Append(" ?? new ").Append(CsName(f.ElementType)).Append("();\n");
                        sb.Append(pad).Append("    ").Append(rd).Append("(o2, r);\n");
                        sb.Append(pad).Append("    ").Append(lv).Append(" = o2;\n");
                        sb.Append(pad).Append("}\n");
                    }
                    break;
                }
            case SerializedType.Kind.List:
                {
                    string et = CsName(f.ElementType);
                    bool isArray = f.Info.FieldType.IsArray;
                    sb.Append(pad).Append("int cnt = r.I32();\n");
                    sb.Append(pad).Append("if (cnt >= 0)\n");
                    sb.Append(pad).Append("{\n");
                    sb.Append(pad).Append("    var tmp = ").Append(isArray ? "new " + et + "[cnt]" : "new global::System.Collections.Generic.List<" + et + ">()").Append(";\n");
                    sb.Append(pad).Append("    for (int k = 0; k < cnt; k++)\n");
                    sb.Append(pad).Append("    {\n");
                    string store = isArray ? "tmp[k] = {0};" : "tmp.Add({0});";
                    switch (f.ElementKind)
                    {
                        case SerializedType.Kind.GoRef:
                        case SerializedType.Kind.CompRef:
                            {
                                string fn = f.ElementKind == SerializedType.Kind.GoRef ? "GoRef" : "CompRef";
                                if (!isArray)
                                    sb.Append(pad).Append("        tmp.Add(null);\n");
                                sb.Append(pad).Append("        int kk = k;\n");
                                sb.Append(pad).Append("        r.").Append(fn).Append("(v => tmp[kk] = (").Append(et).Append(")v);\n");
                                break;
                            }
                        case SerializedType.Kind.Object:
                            {
                                string rd = EmitNestedReader(f, idx, nested, ref nestedN, thunks, ref thunkN);
                                if (f.ElementType.IsValueType)
                                {
                                    sb.Append(pad).Append("        var el = default(").Append(et).Append(");\n");
                                    sb.Append(pad).Append("        if (r.U8() != 0) ").Append(rd).Append("(ref el, r);\n");
                                }
                                else
                                {
                                    sb.Append(pad).Append("        var el = new ").Append(et).Append("();\n");
                                    sb.Append(pad).Append("        if (r.U8() != 0) ").Append(rd).Append("(el, r);\n");
                                }
                                sb.Append(pad).Append("        ").Append(string.Format(store, "el")).Append('\n');
                                break;
                            }
                        default:
                            sb.Append(pad).Append("        ").Append(string.Format(store, ScalarExpr(f.ElementKind, et))).Append('\n');
                            break;
                    }
                    sb.Append(pad).Append("    }\n");
                    sb.Append(pad).Append("    ").Append(lv).Append(" = tmp;\n");
                    sb.Append(pad).Append("}\n");
                    break;
                }
            default:
                sb.Append(pad).Append(lv).Append(" = ").Append(ScalarExpr(f.Kind, ft)).Append(";\n");
                break;
        }
    }

    static string ScalarExpr(SerializedType.Kind k, string type) => k switch
    {
        SerializedType.Kind.Float => "r.F32()",
        SerializedType.Kind.Int => "r.I32()",
        SerializedType.Kind.Bool => "r.Bool()",
        SerializedType.Kind.String => "r.String()",
        SerializedType.Kind.Enum => "(" + type + ")r.I32()",
        SerializedType.Kind.Vec2 => "r.V2()",
        SerializedType.Kind.Vec3 => "r.V3()",
        SerializedType.Kind.Vec4 => "r.V4()",
        SerializedType.Kind.Color => "r.Col()",
        SerializedType.Kind.Asset => "(" + type + ")r.Asset(typeof(" + type + "))",
        _ => throw new InvalidOperationException("baked okuyucu: beklenmeyen kind " + k),
    };

    // Ic ice [Serializable] nesne okuyucusu: struct -> ref parametre, class -> referans.
    static string EmitNestedReader(SerializedType.FieldSchema f, int idx, StringBuilder nested, ref int nestedN,
        StringBuilder thunks, ref int thunkN)
    {
        string name = "Read_" + idx + "_n" + nestedN++;
        bool isStruct = f.ElementType.IsValueType;
        var sb = new StringBuilder();
        sb.Append("    static void ").Append(name).Append('(').Append(isStruct ? "ref " : "")
          .Append(CsName(f.ElementType)).Append(" o, global::DigitoyEngine.SceneBinary.Reader r)\n    {\n");
        EmitReadSwitch(sb, f.Nested, "o", isStruct, idx, nested, ref nestedN, thunks, ref thunkN, 2);
        sb.Append("    }\n\n");
        nested.Append(sb);
        return name;
    }

    // Alan lvalue'su: public -> dogrudan; private/readonly -> UnsafeAccessor ref-thunk.
    static string FieldLValue(FieldInfo fi, string owner, bool ownerIsStruct, int idx, StringBuilder thunks, ref int thunkN)
    {
        if (fi.IsPublic && !fi.IsInitOnly)
            return owner + "." + fi.Name;
        string th = EmitFieldThunk(thunks, fi, idx, ref thunkN);
        return th + "(" + (ownerIsStruct ? "ref " : "") + owner + ")";
    }

    static string CreateExpr(Type t, string tn)
    {
        var ci = t.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
        if (ci != null && (ci.IsPublic || ci.IsAssembly || ci.IsFamilyOrAssembly))
            return "() => new " + tn + "()";
        // private/protected ctor: reflection fallback'iyle ayni davranis
        return "() => (global::DigitoyEngine.Component)global::System.Activator.CreateInstance(typeof(" + tn + "), nonPublic: true)";
    }

    static string CopyToExpr(Type t, string tn, int idx, StringBuilder thunks, ref int thunkN)
    {
        // RegisterReflective ile birebir alan kumesi: public VEYA [SerializeField].
        var sb = new StringBuilder();
        sb.Append("(s0, d0) =>\n            {\n");
        sb.Append("                var s1 = (").Append(tn).Append(")s0; var d1 = (").Append(tn).Append(")d0;\n");
        foreach (var fi in t.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (fi.IsLiteral)
                continue;
            if (!fi.IsPublic && !fi.IsDefined(typeof(SerializeFieldAttribute), false))
                continue;
            if (fi.IsPublic && !fi.IsInitOnly)
            {
                sb.Append("                d1.").Append(fi.Name).Append(" = s1.").Append(fi.Name).Append(";\n");
            }
            else
            {
                string th = EmitFieldThunk(thunks, fi, idx, ref thunkN);
                sb.Append("                ").Append(th).Append("(d1) = ").Append(th).Append("(s1);\n");
            }
        }
        sb.Append("            }");
        return sb.ToString();
    }

    // [UnsafeAccessor] ref-thunk: private/readonly alan erisimi (gorunurluk bypass).
    // Struct sahibi: ref parametre (boxed kopyaya degil box'in icine yazilir).
    static string EmitFieldThunk(StringBuilder thunks, FieldInfo fi, int idx, ref int thunkN)
    {
        string name = "F" + idx + "_" + thunkN++;
        thunks.Append("    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = ")
              .Append(Quote(fi.Name)).Append(")]\n");
        thunks.Append("    static extern ref ").Append(CsName(fi.FieldType)).Append(' ').Append(name)
              .Append('(').Append(fi.DeclaringType.IsValueType ? "ref " : "").Append(CsName(fi.DeclaringType)).Append(" o);\n\n");
        return name;
    }

    // Sema dizisi (nested Object/List-of-Object icin ozyinelemeli alt diziler).
    static void EmitSchemaArray(StringBuilder sb, SerializedType.FieldSchema[] schema, string var,
        int idx, StringBuilder thunks, ref int thunkN)
    {
        // Once alt diziler (degisken bildirimi kullanim oncesi olsun).
        for (int i = 0; i < schema.Length; i++)
            if (schema[i].Nested != null)
                EmitSchemaArray(sb, schema[i].Nested, var + "_" + i, idx, thunks, ref thunkN);

        sb.Append("        var ").Append(var).Append(" = new global::DigitoyEngine.SerializedType.FieldSchema[").Append(schema.Length).Append("];\n");
        for (int i = 0; i < schema.Length; i++)
        {
            var f = schema[i];
            sb.Append("        ").Append(var).Append('[').Append(i).Append("] = new global::DigitoyEngine.SerializedType.FieldSchema\n        {\n");
            sb.Append("            Name = ").Append(Quote(f.Name)).Append(",\n");
            if (f.FormerName != null)
                sb.Append("            FormerName = ").Append(Quote(f.FormerName)).Append(",\n");
            sb.Append("            Kind = ").Append(KindExpr(f.Kind)).Append(",\n");
            if (f.Kind == SerializedType.Kind.List)
                sb.Append("            ElementKind = ").Append(KindExpr(f.ElementKind)).Append(",\n");
            if (f.ElementType != null)
                sb.Append("            ElementType = typeof(").Append(CsName(f.ElementType)).Append("),\n");
            if (f.Nested != null)
                sb.Append("            Nested = ").Append(var).Append('_').Append(i).Append(",\n");
            sb.Append("            FieldType = typeof(").Append(CsName(f.Info.FieldType)).Append("),\n");
            sb.Append("            DeclaringType = typeof(").Append(CsName(f.Info.DeclaringType)).Append("),\n");
            EmitBoxedAccessors(sb, f, idx, thunks, ref thunkN);
            EmitContainerCtors(sb, f);
            sb.Append("        };\n");
        }
        // ShowIf: cozulmus kardes referanslari indeksle geri baglanir.
        for (int i = 0; i < schema.Length; i++)
        {
            var f = schema[i];
            if (f.ShowIf == null)
                continue;
            int j = Array.IndexOf(schema, f.ShowIf);
            if (j < 0)
                continue;
            sb.Append("        ").Append(var).Append('[').Append(i).Append("].ShowIf = ").Append(var).Append('[').Append(j).Append("];\n");
            if (f.ShowIfScalar != null)
                sb.Append("        ").Append(var).Append('[').Append(i).Append("].ShowIfScalar = ").Append(Quote(f.ShowIfScalar)).Append(";\n");
        }
    }

    // Boxed Get/Set: release serializer/clone yolunun tek erisim kapisi.
    // Struct sahibi: Set box'in icine Unsafe.Unbox ref'iyle yazar (kopyaya degil).
    static void EmitBoxedAccessors(StringBuilder sb, SerializedType.FieldSchema f,
        int idx, StringBuilder thunks, ref int thunkN)
    {
        var fi = f.Info;
        string decl = CsName(fi.DeclaringType);
        string ft = CsName(fi.FieldType);
        bool structOwner = fi.DeclaringType.IsValueType;
        string unbox = "global::System.Runtime.CompilerServices.Unsafe.Unbox<" + decl + ">(o)";
        string getAccess, setAccess;
        if (fi.IsPublic && !fi.IsInitOnly)
        {
            getAccess = "((" + decl + ")o)." + fi.Name;
            setAccess = structOwner ? unbox + "." + fi.Name : getAccess;
        }
        else
        {
            string th = EmitFieldThunk(thunks, fi, idx, ref thunkN);
            getAccess = setAccess = th + "(" + (structOwner ? "ref " + unbox : "(" + decl + ")o") + ")";
        }
        // Boxing yalniz deger tipinde (alan ya da sahibi struct): o yol AOT disi. Referans alanlar
        // (GoRef/CompRef/Asset/nesne/liste) boxing'siz -> AOT'ta da kalir (GameObject.RemapRefs klonlamada kullanir).
        bool boxes = fi.FieldType.IsValueType || structOwner;
        if (boxes) sb.Append("#if !DE_AOT\n");
        sb.Append("            Get = o => ").Append(getAccess).Append(",\n");
        sb.Append("            Set = (o, v) => ").Append(setAccess).Append(" = (").Append(ft).Append(")v,\n");
        if (boxes) sb.Append("#endif\n");
    }

    static void EmitContainerCtors(StringBuilder sb, SerializedType.FieldSchema f)
    {
        if (f.Kind == SerializedType.Kind.List)
        {
            string et = CsName(f.ElementType);
            if (f.Info.FieldType.IsArray)
                sb.Append("            NewArray = n => new ").Append(et).Append("[n],\n");
            else
                sb.Append("            NewList = () => new global::System.Collections.Generic.List<").Append(et).Append(">(),\n");
        }
        if (f.ElementType != null && (f.Kind == SerializedType.Kind.Object
            || f.ElementKind == SerializedType.Kind.Object || f.ElementType.IsValueType))
        {
            string et = CsName(f.ElementType);
            if (f.ElementType.IsValueType)
                sb.Append("#if !DE_AOT\n"); // struct boxing: yalniz object-tabanli editor yolu
            sb.Append("            NewElement = () => ")
              .Append(f.ElementType.IsValueType ? "(object)default(" + et + ")" : "new " + et + "()")
              .Append(",\n");
            if (f.ElementType.IsValueType)
                sb.Append("#endif\n");
        }
    }

    // --- Animatable tablosu: AnimRegistry.BuildReflective ile AYNI kume ve sira ---
    // (sema yuruyusu ic ice yollarla, sonra [Animatable] property/alan/tetik).
    // Her giris tipli Get/Set lambda: boxing yok, AOT'de reflection yok. Private
    // uyeler UnsafeAccessor thunk'lariyla (alan: ref, property/metod: cagri).
    static void EmitAnimArray(StringBuilder sb, TypeCatalog.Entry e, int idx, StringBuilder thunks, ref int thunkN)
    {
        var t = e.Type;
        string tn = CsName(t);
        string self = "((" + tn + ")c)";
        var items = new List<string>();
        var paths = new List<string>();

        if (e.Schema != null)
            WalkAnim(e.Schema, "", self, false, tn, idx, items, paths, thunks, ref thunkN, 0);

        foreach (var pi in t.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (!pi.IsDefined(typeof(AnimatableAttribute), false) || !AnimRegistry.TryKind(pi.PropertyType, out var k))
                continue;
            if (pi.GetMethod == null || pi.SetMethod == null)
                continue;
            string get, setFmt;
            if (pi.GetMethod.IsPublic && pi.SetMethod.IsPublic)
            {
                get = self + "." + pi.Name;
                setFmt = get + " = {0}";
            }
            else
            {
                get = EmitMethodThunk(thunks, pi.GetMethod, idx, ref thunkN) + "(" + self + ")";
                setFmt = EmitMethodThunk(thunks, pi.SetMethod, idx, ref thunkN) + "(" + self + ", {0})";
            }
            items.Add(AnimItem(pi.Name, k, pi.PropertyType, tn, get, setFmt));
            paths.Add(pi.Name);
        }
        foreach (var fi in t.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (!fi.IsDefined(typeof(AnimatableAttribute), false) || !AnimRegistry.TryKind(fi.FieldType, out var k))
                continue;
            if (paths.Contains(fi.Name))
                continue; // serilesen alan zaten listede
            string lv = FieldLValue(fi, self, false, idx, thunks, ref thunkN);
            items.Add(AnimItem(fi.Name, k, fi.FieldType, tn, lv, lv + " = {0}"));
            paths.Add(fi.Name);
        }
        foreach (var mi in t.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (!mi.IsDefined(typeof(AnimatableAttribute), false) || mi.GetParameters().Length != 0 || mi.ReturnType != typeof(void))
                continue;
            string call = mi.IsPublic
                ? self + "." + mi.Name + "()"
                : EmitMethodThunk(thunks, mi, idx, ref thunkN) + "(" + self + ")";
            items.Add("new global::DigitoyEngine.AnimProperty { Path = " + Quote(mi.Name)
                + ", Kind = global::DigitoyEngine.AnimKind.Trigger, OwnerType = typeof(" + tn
                + "), ValueType = typeof(void), Set = (c, v) => " + call + " },");
        }

        sb.Append("        var a = new global::DigitoyEngine.AnimProperty[]\n        {\n");
        foreach (var it in items)
            sb.Append("            ").Append(it).Append('\n');
        sb.Append("        };\n");
    }

    static void WalkAnim(SerializedType.FieldSchema[] schema, string prefix, string owner, bool ownerIsStruct,
        string ownerTn, int idx, List<string> items, List<string> paths, StringBuilder thunks, ref int thunkN, int depth)
    {
        foreach (var f in schema)
        {
            string path = prefix + f.Name;
            var fi = f.Info;
            if (fi == null)
                continue;
            string lv = FieldLValue(fi, owner, ownerIsStruct, idx, thunks, ref thunkN);
            if (f.Kind == SerializedType.Kind.Object && f.Nested != null && depth < 6)
            {
                WalkAnim(f.Nested, path + ".", lv, f.ElementType.IsValueType, ownerTn, idx, items, paths, thunks, ref thunkN, depth + 1);
                continue;
            }
            if (!AnimRegistry.TryKind(fi.FieldType, out var k))
                continue;
            items.Add(AnimItem(path, k, fi.FieldType, ownerTn, lv, lv + " = {0}"));
            paths.Add(path);
        }
    }

    // AnimValue donusumleri AnimRegistry.Add ile ayna. setFmt: {0} = v'den cozulmus deger.
    static string AnimItem(string path, AnimKind kind, Type valueType, string ownerTn, string get, string setFmt)
    {
        string vt = CsName(valueType);
        const string AV = "global::DigitoyEngine.AnimValue.";
        string from, to;
        switch (kind)
        {
            case AnimKind.Float: from = AV + "FromFloat(" + get + ")"; to = "v.ToFloat()"; break;
            case AnimKind.Int: from = AV + "FromInt(" + get + ")"; to = "v.ToInt()"; break;
            case AnimKind.Bool: from = AV + "FromBool(" + get + ")"; to = "v.ToBool()"; break;
            case AnimKind.Enum: from = AV + "FromInt((int)" + get + ")"; to = "(" + vt + ")v.ToInt()"; break;
            case AnimKind.Vec2: from = AV + "FromVec2(" + get + ")"; to = "v.ToVec2()"; break;
            case AnimKind.Vec3: from = AV + "FromVec3(" + get + ")"; to = "v.ToVec3()"; break;
            case AnimKind.Vec4: from = AV + "FromVec4(" + get + ")"; to = "v.ToVec4()"; break;
            case AnimKind.Color: from = AV + "FromColor(" + get + ")"; to = "v.ToColor()"; break;
            case AnimKind.Ref: from = AV + "FromRef((object)" + get + ")"; to = "(" + vt + ")v.Ref"; break;
            default: throw new InvalidOperationException("anim emitter: beklenmeyen kind " + kind);
        }
        return "new global::DigitoyEngine.AnimProperty { Path = " + Quote(path)
            + ", Kind = global::DigitoyEngine.AnimKind." + kind
            + ", OwnerType = typeof(" + ownerTn + "), ValueType = typeof(" + vt + ")"
            + ", Get = c => " + from
            + ", Set = (c, v) => " + setFmt.Replace("{0}", to) + " },";
    }

    // Private property erisimcisi / tetik metodu: UnsafeAccessor cagri thunk'i.
    static string EmitMethodThunk(StringBuilder thunks, MethodInfo mi, int idx, ref int thunkN)
    {
        string name = "M" + idx + "_" + thunkN++;
        thunks.Append("    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = ")
              .Append(Quote(mi.Name)).Append(")]\n");
        thunks.Append("    static extern ").Append(mi.ReturnType == typeof(void) ? "void" : CsName(mi.ReturnType))
              .Append(' ').Append(name).Append('(').Append(CsName(mi.DeclaringType)).Append(" o");
        var ps = mi.GetParameters();
        for (int i = 0; i < ps.Length; i++)
            thunks.Append(", ").Append(CsName(ps[i].ParameterType)).Append(" a").Append(i);
        thunks.Append(");\n\n");
        return name;
    }

    static string KindExpr(SerializedType.Kind k)
        => "global::DigitoyEngine.SerializedType.Kind." + k;

    // --- tip erisilebilirligi + C# adi ---

    // Uretilen kod ayri assembly'de (Digitoy.Registry): public/internal (IVT) gorunur,
    // private/protected nested gorunmez. Generic tanimlar kayit edilemez.
    static bool CanEmit(TypeCatalog.Entry e)
    {
        var t = e.Type;
        if (t.IsGenericTypeDefinition || t.ContainsGenericParameters)
            return false;
        if (!Accessible(t))
            return false;
        // Sema/copy'de adi gecen tum tipler de gorunur olmali (Set cast'i +
        // typeof(FieldType) her serilesen alanin tipini kodda adlandirir).
        foreach (var fi in t.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
        {
            if (fi.IsLiteral || (!fi.IsPublic && !fi.IsDefined(typeof(SerializeFieldAttribute), false)
                && !fi.IsDefined(typeof(AnimatableAttribute), false)))
                continue;
            if (!Accessible(fi.DeclaringType) || !Accessible(fi.FieldType))
                return false;
        }
        // [Animatable] property/tetik: Anim tablosu tipleri + sahibi kodda adlandirir.
        foreach (var pi in t.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
            if (pi.IsDefined(typeof(AnimatableAttribute), false) && (!Accessible(pi.DeclaringType) || !Accessible(pi.PropertyType)))
                return false;
        foreach (var mi in t.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
            if (mi.IsDefined(typeof(AnimatableAttribute), false) && !Accessible(mi.DeclaringType))
                return false;
        return SchemaTypesAccessible(e.Schema);
    }

    static bool SchemaTypesAccessible(SerializedType.FieldSchema[] schema)
    {
        if (schema == null)
            return true;
        foreach (var f in schema)
        {
            if (!Accessible(f.Info.DeclaringType))
                return false;
            if (f.ElementType != null && !Accessible(f.ElementType))
                return false;
            if (f.Nested != null && !SchemaTypesAccessible(f.Nested))
                return false;
        }
        return true;
    }

    internal static bool Accessible(Type t)
    {
        if (t == null)
            return false;
        if (t.IsArray || t.IsByRef || t.IsPointer)
            return Accessible(t.GetElementType());
        if (t.IsGenericParameter)
            return false;
        if (t.IsGenericType)
            foreach (var a in t.GetGenericArguments())
                if (!Accessible(a))
                    return false;
        for (var x = t; x != null; x = x.DeclaringType)
        {
            if (x.IsNested)
            {
                if (x.IsNestedPrivate || x.IsNestedFamily || x.IsNestedFamANDAssem)
                    return false; // IVT private/protected'i acmaz
            }
            else
            {
                return true; // top-level: public veya internal (IVT ile gorunur)
            }
        }
        return true;
    }

    internal static string CsName(Type t)
    {
        if (t.IsArray)
            return CsName(t.GetElementType()) + "[]";
        var sb = new StringBuilder();
        BuildName(t, sb);
        return sb.ToString();
    }

    static void BuildName(Type t, StringBuilder sb)
    {
        if (t.DeclaringType != null)
        {
            BuildName(t.DeclaringType, sb);
            sb.Append('.');
        }
        else
        {
            sb.Append("global::");
            if (!string.IsNullOrEmpty(t.Namespace))
                sb.Append(t.Namespace).Append('.');
        }
        string n = t.Name;
        int tick = n.IndexOf('`');
        if (tick >= 0)
            n = n.Substring(0, tick);
        sb.Append(n);
        if (t.IsGenericType)
        {
            sb.Append('<');
            var args = t.GetGenericArguments();
            for (int i = 0; i < args.Length; i++)
            {
                if (i > 0)
                    sb.Append(", ");
                sb.Append(CsName(args[i]));
            }
            sb.Append('>');
        }
    }

    static string Quote(string s)
    {
        var sb = new StringBuilder(s.Length + 8);
        sb.Append('"');
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
