// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

using System;
using UnityEngine.Scripting;
using System.Runtime.InteropServices;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using UnityEngine.Bindings;
using Unity.Scripting.LifecycleManagement;

namespace UnityEngine
{
    ///<summary>Global physics properties and helper methods.</summary>
    public partial class Physics
    {
        ///<summary>Subscribe to this event to be able to customize the collision response for contact pairs.</summary>
        ///<remarks>Each subscriber to this event gets invoked with a physics scene and a native array of contact pairs to process. Each contact pair has modifiable data, like impulses and contact normals that can be changed in order to customize the bounce behavior.
        ///
        ///Only pairs containing Colliders that had <see cref="Collider.hasModifiableContacts" /> enabled will be passed in the buffer.
        ///
        ///Note that this event is called from any thread, so it's advisable to keep copies of all necessary for handling data because only a portion of Unity API is available off the main thread.
        ///
        ///Additionally, an event handler can be invoked multiple times per frame, because the physics system distributes all contacts among threads, and only sends a particular amount of contacts per call.
        ///
        ///Note: to get contact pairs that have been generated by the CCD solver, subscribe to the <see cref="Physics.ContactModifyEventCCD" /> event. They are not included in this event.</remarks>
        ///<example>
        ///  <code><![CDATA[
        ///using Unity.Collections;
        ///using UnityEngine;
        ///
        ///public class Test : MonoBehaviour
        ///{
        ///    public float IgnoredRadius = 0.5f;
        ///    public Vector3 SpawnAt = Vector3.up * 5f;
        ///
        ///    public void OnEnable()
        ///    {
        ///        var ball = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        ///        GameObject.CreatePrimitive(PrimitiveType.Plane);
        ///
        ///        ball.transform.position = SpawnAt;
        ///        ball.AddComponent<Rigidbody>();
        ///        ball.GetComponent<SphereCollider>().hasModifiableContacts = true;
        ///
        ///        Physics.ContactModifyEvent += ModificationEvent;
        ///    }
        ///
        ///    public void OnDisable()
        ///    {
        ///        Physics.ContactModifyEvent -= ModificationEvent;
        ///    }
        ///
        ///    public void ModificationEvent(PhysicsScene scene, NativeArray<ModifiableContactPair> pairs)
        ///    {
        ///        // For each contact pair, ignore the contact points that are close to origin
        ///        foreach (var pair in pairs)
        ///        {
        ///            for (int i = 0; i < pair.contactCount; ++i)
        ///                if (Vector3.Distance(pair.GetPoint(i), Vector3.zero) < IgnoredRadius)
        ///                    pair.IgnoreContact(i);
        ///        }
        ///    }
        ///}
        ///]]></code>
        ///</example>
        [AutoStaticsCleanupOnCodeReload]
        public static event Action<PhysicsScene, NativeArray<ModifiableContactPair>> ContactModifyEvent;
        ///<summary>Subscribe to this event to be able to customize the collision response of CCD generated contact pairs.</summary>
        ///<remarks>Similar to <see cref="Physics.ContactModifyEvent" /> but dedicated to contact pairs that have been generated by the CCD solver. Each subscriber to this event gets invoked with a physics scene, a native array of contact pairs to process. Each contact pair has modifiable data, like impulses and contact normals that can be changed in order to customize the bounce behavior.
        ///
        ///Note: the contact normal in this callback is always inverted. After the callback, physics system inverts it again.</remarks>
        [AutoStaticsCleanupOnCodeReload]
        public static event Action<PhysicsScene, NativeArray<ModifiableContactPair>> ContactModifyEventCCD;
        //initially hook contact modification to always be physx specific
        // No cleanup: this event is never subscribed to by user/reloadable code — its only handler is the
        // core static PhysXOnSceneContactModify (set via the initializer). It pins no reloadable ALC, so there
        // is nothing to leak. It must persist across code reload; clearing it would strip the default handler
        // (the initializer does not re-run on in-place reload) and silently break native contact modification.
        [NoAutoStaticsCleanup]
        internal static event Action<PhysicsScene, IntPtr, int, bool> GenericContactModifyEvent = PhysXOnSceneContactModify;

        [RequiredByNativeCode]
        private static unsafe void OnSceneContactModify(PhysicsScene scene, IntPtr buffer, int count, bool isCCD)
        {
            GenericContactModifyEvent?.Invoke(scene, buffer, count, isCCD);
        }

        private static unsafe void PhysXOnSceneContactModify(PhysicsScene scene, IntPtr buffer, int count, bool isCCD)
        {
            var array = NativeArrayUnsafeUtility.ConvertExistingDataToNativeArray<ModifiableContactPair>(buffer.ToPointer(), count, Allocator.None);

            var safety = AtomicSafetyHandle.Create();
            NativeArrayUnsafeUtility.SetAtomicSafetyHandle(ref array, safety);

            if (!isCCD)
                ContactModifyEvent?.Invoke(scene, array);
            else
                ContactModifyEventCCD?.Invoke(scene, array);

            AtomicSafetyHandle.Release(safety);
        }
    }


    ///<summary>A light-weight proxy that allows to access the contact buffers directly.</summary>
    [StructLayout(LayoutKind.Sequential)]
    [NativeHeader("Modules/Physics/PhysicsCollisionGeometry.h")]
    [NativeHeader("Modules/Physics/PhysXContactModification.h")]
    public struct ModifiableContactPair
    {
        private IntPtr actor;
        private IntPtr otherActor;

        private IntPtr shape;
        private IntPtr otherShape;

        ///<summary>World-space rotation of the first collider in this contact pair as seen by the solver.</summary>
        public Quaternion rotation;
        ///<summary>World-space position of the first collider in this contact pair as seen by the solver.</summary>
        public Vector3 position;

        ///<summary>World-space rotation of the second collider in this contact pair as seen by the solver.</summary>
        public Quaternion otherRotation;
        ///<summary>World-space position of the second collider in this contact pair as seen by the solver.</summary>
        public Vector3 otherPosition;

        private int numContacts;
        private IntPtr contacts;

        [FreeFunction("Physics::PhysXGeometryExtension::TranslateTriangleIndex", true)]
        extern internal static uint TranslateTriangleIndex(IntPtr shapePtr, uint rawIndex);

        [FreeFunction("Physics::PhysXContactModificationExtension::ResolveShapeToEntityId", true)]
        extern internal static EntityId ResolveShapeToEntityId(IntPtr shapePtr);

        [FreeFunction("Physics::PhysXContactModificationExtension::ResolveActorToEntityId", true)]
        extern internal static EntityId ResolveActorToEntityId(IntPtr actorPtr);

        [FreeFunction("Physics::PhysXContactModificationExtension::GetActorLinearVelocity", true)]
        extern internal static Vector3 GetActorLinearVelocity(IntPtr actorPtr);

        [FreeFunction("Physics::PhysXContactModificationExtension::GetActorAngularVelocity", true)]
        extern internal static Vector3 GetActorAngularVelocity(IntPtr actorPtr);

        ///<summary>EntityId of the first Collider in this contact pair.</summary>
        public EntityId colliderEntityId => ResolveShapeToEntityId(shape);
        ///<summary>Obsolete. Use colliderEntityId instead.</summary>
        ///<remarks>Instance ID of the first Collider in this contact pair.</remarks>
        [System.Obsolete("colliderInstanceID is deprecated, use colliderEntityId instead.", true)]
        public int colliderInstanceID => ResolveShapeToEntityId(shape);

        ///<summary>EntityId of the second collider in this contact pair.</summary>
        public EntityId otherColliderEntityId => ResolveShapeToEntityId(otherShape);
        ///<summary>Obsolete. Use otherColliderEntityId instead.</summary>
        ///<remarks>Instance ID of the second collider in this contact pair.</remarks>
        [System.Obsolete("otherColliderInstanceID is deprecated, use otherColliderEntityId instead.", true)]
        public int otherColliderInstanceID => ResolveShapeToEntityId(otherShape);

        ///<summary>EntityId of the first body in this contact pair.</summary>
        ///<remarks>Note that this can be Rigidbody or ArticulationBody.</remarks>
        public EntityId bodyEntityId => ResolveActorToEntityId(actor);
        ///<summary>Obsolete. Use bodyEntityId instead.</summary>
        ///<remarks>Instance ID of the first body in this contact pair. Note that this can be Rigidbody or ArticulationBody.</remarks>
        [System.Obsolete("bodyInstanceID is deprecated, use bodyEntityId instead.", true)]
        public int bodyInstanceID => ResolveActorToEntityId(actor);

        ///<summary>EntityId of the second body in this contact pair.</summary>
        ///<remarks>Note that this can be Rigidbody or ArticulationBody.</remarks>
        public EntityId otherBodyEntityId => ResolveActorToEntityId(otherActor);
        ///<summary>Obsolete. Use otherBodyEntityId instead.</summary>
        ///<remarks>Instance ID of the second body in this contact pair. Note that this can be Rigidbody or ArticulationBody.</remarks>
        [System.Obsolete("otherBodyInstanceID is deprecated, use otherBodyEntityId instead.", true)]
        public int otherBodyInstanceID => ResolveActorToEntityId(otherActor);

        ///<summary>Linear velocity of the first body in the contact pair.</summary>
        public Vector3 bodyVelocity => GetActorLinearVelocity(actor);
        ///<summary>Angular velocity of the first body in the contact pair.</summary>
        public Vector3 bodyAngularVelocity => GetActorAngularVelocity(actor);
        ///<summary>Linear velocity of the second body in the contact pair.</summary>
        public Vector3 otherBodyVelocity => GetActorLinearVelocity(otherActor);
        ///<summary>Angular velocity of the second body in the contact pair.</summary>
        public Vector3 otherBodyAngularVelocity => GetActorAngularVelocity(otherActor);

        ///<summary>The amount of the contact points generated for this contact pair.</summary>
        public int contactCount => numContacts;

        ///<summary>Mass-related properties of this contact pair, such as the mass ratio.</summary>
        public unsafe ModifiableMassProperties massProperties
        {
            get
            {
                return GetContactPatch()->massProperties;
            }

            set
            {
                var contactPatch = GetContactPatch();
                contactPatch->massProperties = value;
                contactPatch->internalFlags |= (byte)ModifiableContactPatch.Flags.HasModifiedMassRatios;
            }
        }

        ///<summary>Get the location of a particular contact point in this contact pair.</summary>
        ///<remarks>The returned value is in the world coodinates.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>The location of a contact point.</returns>
        public unsafe Vector3 GetPoint(int i)
        {
            return GetContact(i)->contact;
        }

        ///<summary>Set the location of a particular contact point in this contact pair.</summary>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="v">The location of a contact point.</param>
        public unsafe void SetPoint(int i, Vector3 v)
        {
            GetContact(i)->contact = v;
        }

        ///<summary>Get the normal at a particular contact point in this contact pair.</summary>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>Normal at the contact point.</returns>
        public unsafe Vector3 GetNormal(int i)
        {
            return GetContact(i)->normal;
        }

        ///<summary>Set the normal at a particular contact point in this contact pair.</summary>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="normal">Normal at the contact point.</param>
        public unsafe void SetNormal(int i, Vector3 normal)
        {
            GetContact(i)->normal = normal;
            GetContactPatch()->internalFlags |= (byte)ModifiableContactPatch.Flags.RegeneratePatches;
        }

        ///<summary>Get the separation value at a particular contact point in this contact pair.</summary>
        ///<remarks>Separation shows the distance between the colliders at this contact point. Negative means the colliders overlap each other. Positive means the colliders are still separated.
        ///
        ///Note that the physics engine starts generating contact pairs when the distance between is lower than the sum of their respective <see cref="Collider.contactOffset" />.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>The separation at a contact point.</returns>
        public unsafe float GetSeparation(int i)
        {
            return GetContact(i)->separation;
        }

        ///<summary>Set the separation value at a particular contact point in this contact pair.</summary>
        ///<remarks>Separation shows the distance between the colliders at this contact point. Negative means the colliders overlap each other. Positive means the colliders are still separated.
        ///
        ///Note that the physics engine starts generating contact pairs when the distance between is lower than the sum of their respective <see cref="Collider.contactOffset" />.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="separation">The separation at a contact point.</param>
        public unsafe void SetSeparation(int i, float separation)
        {
            GetContact(i)->separation = separation;
        }

        ///<summary>Get the target velocity the solver should aim reaching at a particular contact point in this contact pair.</summary>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>The target velocity at a contact point.</returns>
        public unsafe Vector3 GetTargetVelocity(int i)
        {
            return GetContact(i)->targetVelocity;
        }

        ///<summary>Set the target velocity the solver should aim reaching at a particular contact point in this contact pair.</summary>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="velocity">The target velocity at a contact point.</param>
        public unsafe void SetTargetVelocity(int i, Vector3 velocity)
        {
            GetContact(i)->targetVelocity = velocity;
            GetContactPatch()->internalFlags |= (byte)ModifiableContactPatch.Flags.HasTargetVelocity;
        }

        ///<summary>Get the restitution value for the specified contact point in this contact pair.</summary>
        ///<remarks>Restitution value specifies how bouncy the surfaces at the specified contact point are.
        ///
        ///Bounciness of 0 means absolutely not bouncy at all (all the kinetic energy is lost at contact). A value of 1 means all the kinetic energy (and then some due to computational errors) will be conserved. Because of that, normally, bounciness is somewhere in between 0 and 1.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>Bounciness value for the specified contact point.</returns>
        public unsafe float GetBounciness(int i)
        {
            return GetContact(i)->restitution;
        }

        ///<summary>Set the restitution value for the specified contact point in this contact pair.</summary>
        ///<remarks>Restitution value specifies how bouncy the surfaces at the specified contact point are.
        ///
        ///Bounciness of 0 means absolutely not bouncy at all (all the kinetic energy is lost at contact). A value of 1 means all the kinetic energy (and then some due to computational errors) will be conserved. Because of that, normally, bounciness is somewhere in between 0 and 1.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="bounciness">Bounciness value for the specified contact point.</param>
        public unsafe void SetBounciness(int i, float bounciness)
        {
            GetContact(i)->restitution = bounciness;
            GetContactPatch()->internalFlags |= (byte)ModifiableContactPatch.Flags.RegeneratePatches;
        }

        ///<summary>Get the static friction coefficient at a particular point of the contact pair.</summary>
        ///<remarks>Normally, the static friction coefficient is between 0 and 1.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>The static friction coefficient at a contact point.</returns>
        public unsafe float GetStaticFriction(int i)
        {
            return GetContact(i)->staticFriction;
        }

        ///<summary>Set the static friction coefficient at a particular point of the contact pair.</summary>
        ///<remarks>Normally, the static friction coefficient is between 0 and 1.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="staticFriction">The static friction coefficient at a contact point.</param>
        public unsafe void SetStaticFriction(int i, float staticFriction)
        {
            GetContact(i)->staticFriction = staticFriction;
            GetContactPatch()->internalFlags |= (byte)ModifiableContactPatch.Flags.RegeneratePatches;
        }

        ///<summary>Get the value of the dynamic friction for a specified contact point in this contact pair.</summary>
        ///<remarks>Dynamic friction slows down bodies that are sliding over other bodies.
        ///
        ///Normally, it is between 0 and 1.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>Dynamic friction coefficient.</returns>
        public unsafe float GetDynamicFriction(int i)
        {
            return GetContact(i)->dynamicFriction;
        }

        ///<summary>Set the value of the dynamic friction for a specified contact point in this contact pair.</summary>
        ///<remarks>Dynamic friction slows down bodies that are sliding over other bodies.
        ///
        ///Normally, it is between 0 and 1.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="dynamicFriction">Dynamic friction coefficient.</param>
        public unsafe void SetDynamicFriction(int i, float dynamicFriction)
        {
            GetContact(i)->dynamicFriction = dynamicFriction;
            GetContactPatch()->internalFlags |= (byte)ModifiableContactPatch.Flags.RegeneratePatches;
        }

        ///<summary>Get the maximum impulse that the solver can apply at a particular contact point in this contact pair.</summary>
        ///<remarks>Note that setting zero maximum impulse will be the same as disabling the contact point.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>The maximum impulse that can be applied.</returns>
        public unsafe float GetMaxImpulse(int i)
        {
            return GetContact(i)->maxImpulse;
        }

        ///<summary>Set the maximum impulse that the solver can apply at a particular contact point in this contact pair.</summary>
        ///<remarks>Note that setting zero maximum impulse will be the same as disabling the contact point.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<param name="value">The maximum impulse that can be applied.</param>
        public unsafe void SetMaxImpulse(int i, float value)
        {
            GetContact(i)->maxImpulse = value;
            GetContactPatch()->internalFlags |= (byte)ModifiableContactPatch.Flags.HasMaxImpulse;
        }

        ///<summary>Ignore the specified contact point in this contact pair.</summary>
        ///<remarks>Note that this is the same as setting the maximum impulse to be applied at this contact point to zero.</remarks>
        ///<param name="i">Index of the contact point.</param>
        public void IgnoreContact(int i)
        {
            SetMaxImpulse(i, 0);
        }

        ///<summary>Get the index of a face a particular contact point belongs to in this contact pair. Use this with <see cref="Mesh.triangles" />.</summary>
        ///<remarks>Only valid if one of the colliders in this pair is a non-convex MeshCollider. In this case, that collider will always be the second shape of the pair.
        ///A value of 0xffffFFFF indicates an error, which could be none of the Colliders were non-convex MeshColliders, or that the contact point index was out of bounds.</remarks>
        ///<param name="i">Index of the contact point.</param>
        ///<returns>Index of a face this contact point belongs to.</returns>
        public unsafe uint GetFaceIndex(int i)
        {
            if ((GetContactPatch()->internalFlags & (byte)ModifiableContactPatch.Flags.HasFaceIndices) != 0)
            {
                // See PxContactModifyCallback.h:150 for details on this
                var item = new IntPtr(contacts.ToInt64() + numContacts * sizeof(ModifiableContact) + (numContacts + i) * sizeof(int));
                uint rawIndex = *(uint*)item;

                return TranslateTriangleIndex(otherShape, rawIndex);
            }

            return 0xffffFFFF;
        }

        private unsafe ModifiableContact* GetContact(int index)
        {
            var item = new IntPtr(contacts.ToInt64() + index * sizeof(ModifiableContact));
            return (ModifiableContact*)item;
        }

        private unsafe ModifiableContactPatch* GetContactPatch()
        {
            var item = new IntPtr(contacts.ToInt64() - numContacts * sizeof(ModifiableContactPatch));
            return (ModifiableContactPatch*)item;
        }
    }

    ///<summary>Mass-related modifiable properties of a contact pair.</summary>
    ///<remarks>Mostly useful to make a collider appear lighter to the solver than it actually is when the bodies in this contact pair have very different mass values.</remarks>
    [StructLayout(LayoutKind.Sequential)]
    public struct ModifiableMassProperties
    {
        ///<summary>The inverse mass scaling that the solver should apply to the first body of this contact pair.</summary>
        public float inverseMassScale;
        ///<summary>The inverse inertia scaling that the solver should apply to the first body of this contact pair.</summary>
        public float inverseInertiaScale;
        ///<summary>The inverse mass scaling that the solver should apply to the second body of this contact pair.</summary>
        public float otherInverseMassScale;
        ///<summary>The inverse inertia scaling that the solver should apply to the second body of this contact pair.</summary>
        public float otherInverseInertiaScale;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct ModifiableContact
    {
        public Vector3 contact;
        public float separation;
        public Vector3 targetVelocity;
        public float maxImpulse;
        public Vector3 normal;
        public float restitution;
        public uint materialFlags;
        public ushort materialIndex;
        public ushort otherMaterialIndex;
        public float staticFriction;
        public float dynamicFriction;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct ModifiableContactPatch
    {
        // values have to match PxContactPatchFlags from External/PhysX/builds/Include/PxContact.h
        public enum Flags
        {
            HasFaceIndices = 1,
            HasModifiedMassRatios = 8,
            HasTargetVelocity = 16,
            HasMaxImpulse = 32,
            RegeneratePatches = 64,
        };

        public ModifiableMassProperties massProperties;

        public Vector3 normal;
        public float restitution;

        public float dynamicFriction;
        public float staticFriction;
        public byte startContactIndex;
        public byte contactCount;

        public byte materialFlags;
        public byte internalFlags;
        public ushort materialIndex;
        public ushort otherMaterialIndex;
    }
}
