// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

using System;
using UnityEngine.Bindings;
using System.Runtime.InteropServices;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;

namespace UnityEngine.LowLevelPhysics
{
    ///<summary>A transform, containing a position and rotation.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ImmediateTransform
    {
        private Quaternion m_Rotation;
        private Vector3 m_Position;

        ///<summary>The world space rotation of the object.</summary>
        public Quaternion Rotation { get { return m_Rotation; } set { m_Rotation = value; } }
        ///<summary>The world space position of the object.</summary>
        public Vector3 Position { get { return m_Position; } set { m_Position = value; } }
    }

    ///<summary>Describes a contact where two shapes collide.</summary>
    ///<remarks>These contact points are generated by the <see cref="ImmediatePhysics.GenerateContacts" /> function.</remarks>
    [StructLayout(LayoutKind.Sequential)]
    public struct ImmediateContact
    {
        private Vector3 m_Normal;
        private float m_Separation;
        private Vector3 m_Point;

        private float m_MaxImpulse;
        private Vector3 m_TargetVel;
        private float m_StaticFriction;
        private byte m_MaterialFlags;
        private byte m_Pad;
        private ushort m_InternalUse;
        private uint m_InternalFaceIndex1;
        private float m_DynamicFriction;
        private float m_Restitution;

        ///<summary>The normal of the contact point.</summary>
        public Vector3 Normal { get { return m_Normal; } set { m_Normal = value; } }
        ///<summary>The distance between the shapes at the contact point.</summary>
        ///<remarks>A negative separation means the shapes are overlapping.</remarks>
        public float Separation { get { return m_Separation; } set { m_Separation = value; } }
        ///<summary>The position of the contact point in world space.</summary>
        public Vector3 Point { get { return m_Point; } set { m_Point = value; } }
    }

    ///<summary>This class contains methods to run the immediate simulation steps.</summary>
    [NativeHeader("Modules/Physics/ImmediatePhysics.h")]
    public static class ImmediatePhysics
    {
        [FreeFunction("Physics::Immediate::GenerateContacts", isThreadSafe: true)]
        private static unsafe extern int GenerateContacts_Native(void* geom1, void* geom2, void* xform1, void* xform2, int numPairs, void* contacts, int contactArrayLength, void* sizes, int sizesArrayLength, float contactDistance);

        ///<summary>Generates the contact points for all the given pairs of shapes. Stores the resulting contacts in the <see cref="ImmediateContact" /> array, and the number of contacts per each pair in the `outContactCounts` array.</summary>
        ///<remarks>This code sample defines how many pairs of objects PhysX should expect in the scene. You can set a specific number for a small contact check or, if you intend to run a more complex simulation, you might want to implement broadphase filtering to find out how many pairs of objects will interact. The easiest and least performant option is to put all the possible pairs of bodies into a GenerateContacts function that exists in the scene. This example shows a basic setup of manually adding two pairs of bodies and checking for contacts between them.</remarks>
        ///<param name="geom1">The array that holds the first member of each pair of <see cref="GeometryHolder" /> objects with shapes assigned.</param>
        ///<param name="geom2">The array that holds the second member of each pair of <see cref="GeometryHolder" /> objects with shapes assigned.</param>
        ///<param name="xform1">The array that holds the first member of each pair of <see cref="ImmediateTransform" />s.</param>
        ///<param name="xform2">The array that holds the second member of each pair of <see cref="ImmediateTransform" />s.</param>
        ///<param name="pairCount">The number of pairs provided in the <see cref="GeometryHolder" /> and <see cref="ImmediateTransform" /> arrays.</param>
        ///<param name="outContacts">The output array of contacts that were generated.</param>
        ///<param name="outContactCounts">The output array of how many contacts were generated for each pair.</param>
        ///<param name="contactDistance">The distance at which contacts begin to be generated between the pairs.</param>
        ///<returns>Returns the total number of contact points that were generated.</returns>
        ///<example>
        ///  <code><![CDATA[using System.Collections.Generic;
        ///using UnityEngine;
        ///using UnityEngine.LowLevelPhysics;
        ///using Unity.Collections;
        ///
        ///public class ImmediatePhysics_GenerateContacts_Example : MonoBehaviour
        ///{
        ///    private int m_NumberOfPairs = 2;
        ///
        ///    // Pull in a reference from the Editor to the Mesh Collider.
        ///    [SerializeField]
        ///    private MeshCollider m_Mesh;
        ///
        ///    List<Vector3> contactPoints = new List<Vector3>();
        ///
        ///    // There is no way to know how many contacts the shapes will generate,
        ///    // so set a maximum value that should confidently fit all of them.
        ///    int s_MaxContactCount = 100;
        ///
        ///    void Start()
        ///    {
        ///        // Create and set up geometry and transform arrays.
        ///        NativeArray<GeometryHolder> geom1 = new NativeArray<GeometryHolder>(m_NumberOfPairs, Allocator.Temp);
        ///        NativeArray<GeometryHolder> geom2 = new NativeArray<GeometryHolder>(m_NumberOfPairs, Allocator.Temp);
        ///
        ///        // Create a box shape that is 1 meter wide on each axis, and use that to construct a GeometryHolder object.
        ///        BoxGeometry boxShape = new BoxGeometry(new Vector3(0.5f, 0.5f, 0.5f));
        ///        GeometryHolder box = GeometryHolder.Create(boxShape);
        ///
        ///        // Get the geometry of an existing collider.
        ///        GeometryHolder convexMesh = m_Mesh.GeometryHolder;
        ///
        ///        NativeArray<ImmediateTransform> xForms1 = new NativeArray<ImmediateTransform>(m_NumberOfPairs, Allocator.Temp);
        ///        NativeArray<ImmediateTransform> xForms2 = new NativeArray<ImmediateTransform>(m_NumberOfPairs, Allocator.Temp);
        ///
        ///        ImmediateTransform body1Transform = new ImmediateTransform
        ///        {
        ///            Position = new Vector3(0, 0, 0),
        ///            Rotation = Quaternion.identity
        ///        };
        ///
        ///        ImmediateTransform body2Transform = new ImmediateTransform
        ///        {
        ///            Position = new Vector3(0, 0.75f, 0),
        ///            Rotation = Quaternion.Euler(new Vector3(45f, 0, 0))
        ///        };
        ///
        ///
        ///        // First pair is two boxes interacting.
        ///        geom1[0] = box;
        ///        geom2[0] = box;
        ///
        ///        xForms1[0] = body1Transform;
        ///        xForms2[0] = body2Transform;
        ///
        ///        // Second pair is a box and a convex Mesh Collider.
        ///        geom1[1] = convexMesh;
        ///        geom1[2] = box;
        ///
        ///        xForms1[1] = body1Transform;
        ///        xForms2[1] = body2Transform;
        ///
        ///        // This code re-uses the same transforms, which means that if all the bodies
        ///        // were part of the same simulation, they would all overlap with each other. However,
        ///        // because we are only generating contacts per pair, one pair of bodies does not affect
        ///        // the other pairs.
        ///
        ///        // Create a place to hold the output contacts and their counts per pair.
        ///        // There is no way to know how many contacts the shapes will generate,
        ///        // so set a maximum value that should confidently fit all of them.
        ///        NativeArray<ImmediateContact> contacts = new NativeArray<ImmediateContact>(s_MaxContactCount, Allocator.Temp);
        ///        // The number of contactCounts is the same as the number of pairs.
        ///        NativeArray<int> contactCounts = new NativeArray<int>(m_NumberOfPairs, Allocator.Temp);
        ///
        ///        // Finally, call the GenerateContacts function and put all the arrays in. 
        ///        // Keep note of the ReadOnly status of the input arrays.
        ///
        ///        var totalContacts = ImmediatePhysics.GenerateContacts(geom1.AsReadOnly(), geom2.AsReadOnly(), xForms1.AsReadOnly(), xForms2.AsReadOnly(), m_NumberOfPairs, contacts, contactCounts);
        ///
        ///        // It is now possible to check whether there were any contacts for the pairs.
        ///        // First, iterate over the number of input pairs defined in m_NumberOfPairs.
        ///        int idx = 0;
        ///        for (int i = 0; i < m_NumberOfPairs; i++)
        ///        {
        ///            // Iterate over the number of contacts that were generated per each pair.
        ///            for (int j = 0; j < contactCounts[i]; j++)
        ///            {
        ///                // Add the contact points to a list for visualization later.
        ///                contactPoints.Add(contacts[idx].Point);
        ///
        ///                // The number of contact points per each pair can be variable, so
        ///                // use a separate index to keep track of which contact to retrieve.
        ///                idx++;
        ///            }
        ///        }
        ///    }
        ///}]]></code>
        ///</example>
        public unsafe static int GenerateContacts(NativeArray<GeometryHolder>.ReadOnly geom1, NativeArray<GeometryHolder>.ReadOnly geom2,
            NativeArray<ImmediateTransform>.ReadOnly xform1, NativeArray<ImmediateTransform>.ReadOnly xform2, int pairCount,
            NativeArray<ImmediateContact> outContacts, NativeArray<int> outContactCounts, float contactDistance = 0.01f)
        {
            if (geom1.Length < pairCount ||
                geom2.Length < pairCount ||
                xform1.Length < pairCount ||
                xform2.Length < pairCount)
                throw new ArgumentException("Provided geometry or transform arrays are not large enough to fit the count of pairs.");

            if (pairCount > outContactCounts.Length)
                throw new ArgumentException("The output contact counts array is not big enough. The size of the array needs to match or exceed the amount of pairs.");

            if (contactDistance <= 0)
                throw new ArgumentException("Contact distance must be positive and not equal to zero.");

            return GenerateContacts_Native(
                geom1.GetUnsafeReadOnlyPtr(),
                geom2.GetUnsafeReadOnlyPtr(),
                xform1.GetUnsafeReadOnlyPtr(),
                xform2.GetUnsafeReadOnlyPtr(),
                pairCount,
                outContacts.GetUnsafePtr(),
                outContacts.Length,
                outContactCounts.GetUnsafePtr(),
                outContactCounts.Length,
                contactDistance);
        }
    }
}
