// Unity C# reference source
// Copyright (c) Unity Technologies. For terms of use, see
// https://unity3d.com/legal/licenses/Unity_Reference_Only_License

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using UnityEngine.Bindings;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using UnityEngine.Scripting;

[assembly: InternalsVisibleTo("UnityEngine.VideoModule")]

namespace UnityEngine.Experimental.Audio
{
    ///<summary>Provides access to the audio samples generated by Unity objects such as VideoPlayer.</summary>
    ///<remarks>
    ///  <para>This class is meant to be usable outside the main thread and the implementation assumes a single consumer at a time invoking <see cref="Experimental.Audio.AudioSampleProvider.ConsumeSampleFrames" />. Audio data can be accessed both from C# and from C++, depending on what has to be done with this data.
    ///
    ///The following is an example of how to access samples from C# using an accessor obtained from the <see cref="T:UnityEngine.Video.VideoPlayer" />:</para>
    ///  <para>The following is an example of how to access samples from C++. The setup has to be done in C# and then Unity's core and the native plug-in can call into each other without having to go through managed code.</para>
    ///  <para>And here is the accompanying C++ plug-in:</para>
    ///</remarks>
    ///<example>
    ///  <code><![CDATA[
    ///using UnityEngine;
    ///using Unity.Collections;
    ///using UnityEngine.Experimental.Video;
    ///using UnityEngine.Experimental.Audio;
    ///using UnityEngine.Video;
    ///
    ///public class ManagedAudioOutput : MonoBehaviour
    ///{
    ///    AudioSampleProvider provider;
    ///
    ///    void Start()
    ///    {
    ///        VideoPlayer vp = GetComponent<VideoPlayer>();
    ///        vp.audioOutputMode = VideoAudioOutputMode.APIOnly;
    ///        vp.prepareCompleted += Prepared;
    ///        vp.Prepare();
    ///    }
    ///
    ///    void Prepared(VideoPlayer vp)
    ///    {
    ///        provider = vp.GetAudioSampleProvider(0);
    ///        provider.sampleFramesAvailable += SampleFramesAvailable;
    ///        provider.enableSampleFramesAvailableEvents = true;
    ///        provider.freeSampleFrameCountLowThreshold = provider.maxSampleFrameCount / 4;
    ///        vp.Play();
    ///    }
    ///
    ///    void SampleFramesAvailable(AudioSampleProvider provider, uint sampleFrameCount)
    ///    {
    ///        using (NativeArray<float> buffer = new NativeArray<float>(
    ///                       (int)sampleFrameCount * provider.channelCount, Allocator.Temp))
    ///        {
    ///            var sfCount = provider.ConsumeSampleFrames(buffer);
    ///            Debug.LogFormat("SetupSoftwareAudioOut.Available got {0} sample frames.", sfCount);
    ///            // Do something with the samples here...
    ///        }
    ///    }
    ///}
    ///]]></code>
    ///</example>
    ///<example nocheck="true">
    ///  <code><![CDATA[
    ///using System;
    ///using System.Runtime.InteropServices;
    ///using UnityEngine;
    ///using UnityEngine.Experimental.Video;
    ///using UnityEngine.Experimental.Audio;
    ///using UnityEngine.Video;
    ///
    ///public class NativeAudioOutput : MonoBehaviour
    ///{
    ///    AudioSampleProvider provider;
    ///    AudioSampleProvider.SampleFramesEventNativeFunction sampleFramesAvailableNativeHandler =
    ///        SampleFramesAvailable;
    ///
    ///    void Start()
    ///    {
    ///        VideoPlayer vp = GetComponent<VideoPlayer>();
    ///        vp.audioOutputMode = VideoAudioOutputMode.APIOnly;
    ///        vp.prepareCompleted += Prepared;
    ///        vp.Prepare();
    ///    }
    ///
    ///    void Prepared(VideoPlayer vp)
    ///    {
    ///        provider = vp.GetAudioSampleProvider(0);
    ///        provider.freeSampleFrameCountLowThreshold = provider.maxSampleFrameCount - 1024;
    ///
    ///        SetConsumeSampleFramesFunction(
    ///            AudioSampleProvider.consumeSampleFramesNativeFunction, provider.id,
    ///            provider.channelCount, provider.sampleRate);
    ///        provider.SetSampleFramesAvailableNativeHandler(
    ///            sampleFramesAvailableNativeHandler, (IntPtr)0);
    ///
    ///        vp.Play();
    ///    }
    ///
    ///    private const string pluginName =
    ///#if UNITY_IPHONE
    ///        "__Internal"
    ///#else
    ///        "NativeAudioOutputPlugin"
    ///#endif
    ///    ;
    ///
    ///    [DllImport(pluginName, ExactSpelling = true, CallingConvention = CallingConvention.Cdecl)]
    ///    private static extern void SetConsumeSampleFramesFunction(
    ///        AudioSampleProvider.ConsumeSampleFramesNativeFunction cb, uint id, ushort channelCount, uint sampleRate);
    ///
    ///    [AOT.MonoPInvokeCallback(typeof(AudioSampleProvider.SampleFramesEventNativeFunction))]
    ///    [DllImport(pluginName, ExactSpelling = true, CallingConvention = CallingConvention.Cdecl)]
    ///    private static extern void SampleFramesAvailable(IntPtr userData, uint id, uint sampleFrameCount);
    ///}
    ///]]></code>
    ///</example>
    ///<example nocheck="true">
    ///  <code><![CDATA[
    ///#include <algorithm>
    ///#include <stdint.h>
    ///
    ///typedef uint32_t(__cdecl *ConsumeSampleFramesFunction)(
    ///    uint32_t providerId, float* interleavedSampleFrames, uint32_t sampleFrameCount);
    ///
    ///ConsumeSampleFramesFunction ConsumeSampleFrames = NULL;
    ///uint32_t providerId = -1;
    ///float* buffer = NULL;
    ///uint32_t bufferSampleFrameCount = 0;
    ///uint32_t availableSampleFrameCount = 0;
    ///
    ///extern "C" __cdecl void SetConsumeSampleFramesFunction(
    ///    ConsumeSampleFramesFunction function, uint32_t id, uint16_t channelCount, uint32_t sampleRate)
    ///{
    ///    ConsumeSampleFrames = function;
    ///    providerId = id;
    ///    delete[] buffer;
    ///    buffer = new float[channelCount * sampleRate]; // 1s worth of sample frames.
    ///    bufferSampleFrameCount = sampleRate;
    ///}
    ///
    ///extern "C" __cdecl void SampleFramesAvailable(void* userData, uint32_t id, uint32_t sampleFrameCount)
    ///{
    ///    if (ConsumeSampleFrames == NULL)
    ///        return;
    ///
    ///    // We consume the sample frames from the handler that tells us that there are some available.
    ///    // But we could also invoke this regularly from another thread, for example the thread providing
    ///    // samples to an audio device.
    ///    const uint32_t consumedSampleFrameCount = ConsumeSampleFrames(
    ///            providerId, buffer, std::min(bufferSampleFrameCount, sampleFrameCount));
    ///    // Do something with the samples here...
    ///}
    ///]]></code>
    ///</example>
    [NativeHeader("Modules/Audio/Public/ScriptBindings/AudioSampleProvider.bindings.h")]
    [StaticAccessor("AudioSampleProviderBindings", StaticAccessorType.DoubleColon)]
    public class AudioSampleProvider : IDisposable
    {
        [VisibleToOtherModules]
        static internal AudioSampleProvider Lookup(
            uint providerId, Object ownerObj, ushort trackIndex)
        {
            AudioSampleProvider provider = InternalGetScriptingPtr(providerId);
            if (provider != null || !InternalIsValid(providerId))
                return provider;

            return new AudioSampleProvider(providerId, ownerObj, trackIndex);
        }

        static internal AudioSampleProvider Create(ushort channelCount, uint sampleRate)
        {
            var providerId = InternalCreateSampleProvider(channelCount, sampleRate);
            if (!InternalIsValid(providerId))
                return null;
            return new AudioSampleProvider(providerId, null, 0);
        }

        ///<summary>Type that represents the native function pointer for consuming sample frames.</summary>
        ///<remarks>
        ///  <para>Importing a hypothetical native setup function would be done this way:</para>
        ///  <para>See <see cref="Experimental.Audio.AudioSampleProvider.consumeSampleFramesNativeFunction" /> for how to invoke this native plug-in function.</para>
        ///</remarks>
        ///<param name="providerId">Id of the provider. See <see cref="Experimental.Audio.AudioSampleProvider.id" />.</param>
        ///<param name="interleavedSampleFrames">Pointer to the sample frames buffer to fill. The actual C type is float*.</param>
        ///<param name="sampleFrameCount">Number of sample frames that can be written into interleavedSampleFrames.</param>
        ///<example nocheck="true">
        ///  <code><![CDATA[
        ///[DllImport(pluginName, ExactSpelling = true, CallingConvention = CallingConvention.Cdecl)]
        ///private static extern void SetConsumeSampleFramesFunction(
        ///    AudioSampleProvider.ConsumeSampleFramesNativeFunction cb, uint id, ushort channelCount, uint sampleRate);
        ///]]></code>
        ///</example>
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate uint ConsumeSampleFramesNativeFunction(
            uint providerId, IntPtr interleavedSampleFrames, uint sampleFrameCount);

        private ConsumeSampleFramesNativeFunction m_ConsumeSampleFramesNativeFunction;

        private AudioSampleProvider(uint providerId, Object ownerObj, ushort trackIdx)
        {
            owner = ownerObj;
            id = providerId;
            trackIndex = trackIdx;
            m_ConsumeSampleFramesNativeFunction = (ConsumeSampleFramesNativeFunction)
                Marshal.GetDelegateForFunctionPointer(
                InternalGetConsumeSampleFramesNativeFunctionPtr(),
                typeof(ConsumeSampleFramesNativeFunction));
            ushort chCount = 0;
            uint sRate = 0;
            InternalGetFormatInfo(providerId, out chCount, out sRate);
            channelCount = chCount;
            sampleRate = sRate;
            InternalSetScriptingPtr(providerId, this);
        }

#pragma warning disable UA5000 // The Avoid Finalizer Analyzer produces compile errors for any new finalizers. This pre-existing finalizer declaration has been suppressed, but should be rewritten if possible.
        ~AudioSampleProvider()
        {
            // Nullify owner so Dispose() won't also destroy the native provider.
            owner = null;
            Dispose();
        }
#pragma warning restore UA5000

        ///<summary>Release internal resources. Inherited from IDisposable.</summary>
        public void Dispose()
        {
            if (id != 0)
            {
                InternalSetScriptingPtr(id, null);
                if (owner == null)
                    InternalRemove(id);
                id = 0;
            }
            GC.SuppressFinalize(this);
        }

        ///<summary>Unique identifier for this instance.</summary>
        ///<remarks>This is the id that is expected when invoking the native function pointer <see cref="Experimental.Audio.AudioSampleProvider.consumeSampleFramesNativeFunction" />. This is also the id that is passed in to the native event handlers of type <see cref="Experimental.Audio.AudioSampleProvider.SampleFramesEventNativeFunction" />.
        ///
        ///Identifiers are not recycled throuhout the application' lifetime.</remarks>
        public uint id { get; private set; }

        ///<summary>Index of the track in the object that created this provider.</summary>
        ///<remarks>For providers created by the <see cref="T:UnityEngine.Video.VideoPlayer" />, this is the index of the audio track in the movie file being played.</remarks>
        public ushort trackIndex { get; private set; }

        ///<summary>Object where this provider came from.</summary>
        ///<remarks>E.g.: for <see cref="Experimental.Audio.AudioSampleProvider" />s that were obtained from a <see cref="T:UnityEngine.Video.VideoPlayer" />, this will be the video player.</remarks>
        public Object owner { get; private set; }

        ///<summary>True if the object is valid.</summary>
        ///<remarks>The object becomes invalid when its owner (see <see cref="Experimental.Audio.AudioSampleProvider.owner" /> releases it. However, the provider cannot be destroyed while a call is ongoing so there will be no race condition during destruction.
        ///
        ///A <see cref="T:UnityEngine.Video.VideoPlayer" /> releases all its providers when playback is stopped.</remarks>
        public bool valid { get { return InternalIsValid(id); } }

        ///<summary>The number of audio channels per sample frame.</summary>
        ///<remarks>This property does not change throughout the AudioSampleProvider' life scope.</remarks>
        public ushort channelCount { get; private set; }

        ///<summary>The expected playback rate for the sample frames produced by this class.</summary>
        ///<remarks>This property does not change throughout the AudioSampleProvider' life scope.</remarks>
        public uint sampleRate { get; private set; }

        ///<summary>The maximum number of sample frames that can be accumulated inside the internal buffer before an overflow event is emitted.</summary>
        public uint maxSampleFrameCount
        { get { return InternalGetMaxSampleFrameCount(id); } }

        ///<summary>Number of sample frames available for consuming with <see cref="Experimental.Audio.AudioSampleProvider.ConsumeSampleFrames" />.</summary>
        public uint availableSampleFrameCount
        { get { return InternalGetAvailableSampleFrameCount(id); } }

        ///<summary>Number of sample frames that can still be written to by the sample producer before overflowing.</summary>
        ///<remarks>Letting the internal buffer overflow will emit the <see cref="Experimental.Audio.AudioSampleProvider.sampleFramesOverflow" /> event and invoke the associated native handler set with <see cref="Experimental.Audio.AudioSampleProvider.SetSampleFramesOverflowNativeHandler" />.</remarks>
        public uint freeSampleFrameCount
        { get { return InternalGetFreeSampleFrameCount(id); } }

        ///<summary>When the free sample count falls below this threshold, the <see cref="Experimental.Audio.AudioSampleProvider.sampleFramesAvailable" /> event and associated native is emitted.</summary>
        ///<remarks>The associated native event handler, set with <see cref="Experimental.Audio.AudioSampleProvider.SetSampleFramesAvailableNativeHandler" /> is also invoked.</remarks>
        public uint freeSampleFrameCountLowThreshold
        {
            get { return InternalGetFreeSampleFrameCountLowThreshold(id); }
            set { InternalSetFreeSampleFrameCountLowThreshold(id, value); }
        }

        ///<summary>Enables the <see cref="Experimental.Audio.AudioSampleProvider.sampleFramesAvailable" /> events.</summary>
        ///<remarks>Depending on how often audio sample frames are drained, the sampleFramesAvailable events may be produced at a high rate. Producing these events may cause a unwanted overhead even if they are not monitored, so they can be disabled.
        ///
        ///When sample frames are consumed from a native plug-in, consider using the associated native event handler set via <see cref="Experimental.Audio.AudioSampleProvider.SetSampleFramesAvailableNativeHandler" />.</remarks>
        public bool enableSampleFramesAvailableEvents
        {
            get { return InternalGetEnableSampleFramesAvailableEvents(id); }
            set { InternalSetEnableSampleFramesAvailableEvents(id, value); }
        }

        ///<summary>If true, buffers produced by ConsumeSampleFrames will get padded when silence if there are less available than asked for. Otherwise, the extra sample frames in the buffer will be left unchanged.</summary>
        ///<remarks>Without silence padding, <see cref="Experimental.Audio.AudioSampleProvider.ConsumeSampleFrames" /> will return how many sample frames of the buffer passed were acutally written to, using the available sample frames, and the rest of the buffer will be left intact.
        ///
        ///With silence padding enabled, the method will completely fill the buffer passed in and provide silence if needed, in case there were not enough available sample frames.</remarks>
        public bool enableSilencePadding
        {
            get { return InternalGetEnableSilencePadding(id); }
            set { InternalSetEnableSilencePadding(id, value); }
        }

        ///<summary>Consume sample frames from the internal buffer.</summary>
        ///<remarks>If <see cref="Experimental.Audio.AudioSampleProvider.enableSilencePadding" /> is true, then the buffer passed in will be completely filled and padded with silence if there are less sample frames available than what the buffer can accommodate. Otherwise, the extra sample frames in the buffer will be left intact.</remarks>
        ///<param name="sampleFrames">Buffer where the consumed samples will be transferred.</param>
        ///<returns>How many sample frames were written into the buffer passed in.</returns>
        unsafe public uint ConsumeSampleFrames(NativeArray<float> sampleFrames)
        {
            if (channelCount == 0)
                return 0;

            return m_ConsumeSampleFramesNativeFunction(
                id, (IntPtr)sampleFrames.GetUnsafePtr(), (uint)sampleFrames.Length / channelCount);
        }

        ///<summary>Pointer to the native function that provides access to audio sample frames.</summary>
        ///<remarks>
        ///  <para>This function pointer can be passed to native plug-ins that need to consume sample frames while avoiding any overhead related to going from native to C# or garbage collection interference.
        ///
        ///Importing a native function that uses this type, for passing the native function pointer to the native plugin, would look like this:</para>
        ///  <para>See <see cref="Experimental.Audio.AudioSampleProvider.ConsumeSampleFramesNativeFunction" /> for how to import a native function that uses this signature.</para>
        ///</remarks>
        ///<example nocheck="true">
        ///  <code><![CDATA[
        ///SetConsumeSampleFramesFunction(
        ///    AudioSampleProvider.consumeSampleFramesNativeFunction, signalProvider.id,
        ///    signalProvider.channelCount, signalProvider.sampleRate);
        ///]]></code>
        ///</example>
        public static ConsumeSampleFramesNativeFunction consumeSampleFramesNativeFunction
        {
            get
            {
                return (ConsumeSampleFramesNativeFunction)Marshal.GetDelegateForFunctionPointer(
                    InternalGetConsumeSampleFramesNativeFunctionPtr(),
                    typeof(ConsumeSampleFramesNativeFunction));
            }
        }

        unsafe internal uint QueueSampleFrames(NativeArray<float> sampleFrames)
        {
            if (channelCount == 0)
                return 0;
            return InternalQueueSampleFrames(
                id, (IntPtr)sampleFrames.GetUnsafeReadOnlyPtr(), (uint)(sampleFrames.Length / channelCount));
        }

        ///<summary>Delegate for sample frame events.</summary>
        ///<param name="provider">Provider emitting the event.</param>
        ///<param name="sampleFrameCount">How many sample frames are available, or were dropped, depending on the event.</param>
        public delegate void SampleFramesHandler(
            AudioSampleProvider provider, uint sampleFrameCount);

        ///<summary>Invoked when the number of available sample frames goes beyond the threshold set with <see cref="Experimental.Audio.AudioSampleProvider.freeSampleFrameCountLowThreshold" />.</summary>
        ///<remarks>This event is only emitted when <see cref="Experimental.Audio.AudioSampleProvider.enableSampleFramesAvailableEvents" /> is set to true.</remarks>
        public event SampleFramesHandler sampleFramesAvailable;

        ///<summary>Invoked when the number of available sample frames goes beyond the maximum that fits in the internal buffer.</summary>
        ///<remarks>This event cannot be disabled like the sample frames available counterpart. It is not expected to be frequently emitted so it is not an important source of overhead.</remarks>
        public event SampleFramesHandler sampleFramesOverflow;

        ///<summary>Type that represents the native function pointer for handling sample frame events.</summary>
        ///<remarks>Sample frames events are <see cref="Experimental.Audio.AudioSampleProvider.sampleFramesAvailable" /> and <see cref="Experimental.Audio.AudioSampleProvider.sampleFramesOverflow" />.
        ///
        ///Importing such a function from a native plug-in would be done this way:</remarks>
        ///<param name="userData">User data specified when the handler was set. The actual C type is void*.</param>
        ///<param name="providerId">Id of the provider. See <see cref="Experimental.Audio.AudioSampleProvider.id" />.</param>
        ///<param name="sampleFrameCount">Number of sample frames available or overflowed, depending on event type.</param>
        ///<example nocheck="true">
        ///  <code><![CDATA[
        ///[DllImport(pluginName, ExactSpelling = true, CallingConvention = CallingConvention.Cdecl)]
        ///private static extern void SampleFramesAvailable(IntPtr userData, uint id, uint sampleFrameCount);
        ///]]></code>
        ///</example>
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void SampleFramesEventNativeFunction(
            IntPtr userData, uint providerId, uint sampleFrameCount);

        ///<summary>Set the native event handler for events emitted when the number of available sample frames crosses the threshold.</summary>
        ///<param name="handler">Pointer to the function to invoke when the event is emitted.</param>
        ///<param name="userData">User data to be passed to the handler when invoked. The actual C type is void*.</param>
        public void SetSampleFramesAvailableNativeHandler(
            SampleFramesEventNativeFunction handler, IntPtr userData)
        {
            InternalSetSampleFramesAvailableNativeHandler(
                id, Marshal.GetFunctionPointerForDelegate(handler), userData);
        }

        ///<summary>Clear the native handler set with <see cref="Experimental.Audio.AudioSampleProvider.SetSampleFramesAvailableNativeHandler" />.</summary>
        public void ClearSampleFramesAvailableNativeHandler()
        { InternalClearSampleFramesAvailableNativeHandler(id); }

        ///<summary>Set the native event handler for events emitted when the internal sample frame buffer overflows.</summary>
        ///<param name="handler">Pointer to the function to invoke when the event is emitted.</param>
        ///<param name="userData">User data to be passed to the handler when invoked. The actual C type is void*.</param>
        public void SetSampleFramesOverflowNativeHandler(
            SampleFramesEventNativeFunction handler, IntPtr userData)
        {
            InternalSetSampleFramesOverflowNativeHandler(
                id, Marshal.GetFunctionPointerForDelegate(handler), userData);
        }

        ///<summary>Clear the native handler set with <see cref="Experimental.Audio.AudioSampleProvider.SetSampleFramesOverflowNativeHandler" />.</summary>
        public void ClearSampleFramesOverflowNativeHandler()
        { InternalClearSampleFramesOverflowNativeHandler(id); }

        [RequiredByNativeCode]
        private void InvokeSampleFramesAvailable(int sampleFrameCount)
        {
            if (sampleFramesAvailable != null)
                // ScriptingInvication doesn't support uint, so we get int and cast.
                sampleFramesAvailable(this, (uint)sampleFrameCount);
        }

        [RequiredByNativeCode]
        private void InvokeSampleFramesOverflow(int droppedSampleFrameCount)
        {
            if (sampleFramesOverflow != null)
                sampleFramesOverflow(this, (uint)droppedSampleFrameCount);
        }

        [NativeMethod(IsThreadSafe = true)]
        private static extern uint InternalCreateSampleProvider(ushort channelCount, uint sampleRate);

        [NativeMethod(IsThreadSafe = true)]
        internal static extern void InternalRemove(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern void InternalGetFormatInfo(
            uint providerId, out ushort chCount, out uint sRate);

        private static extern AudioSampleProvider InternalGetScriptingPtr(uint providerId);

        // Can be done outside of the main thread so that garbage-collected provider can be
        // destoryed in any thread. The wanted constraint (must lookup from main thread) is enforced
        // by the fact that InternalGetScriptingPtr _must_ be called from the main thread.
        [NativeMethod(IsThreadSafe = true)]
        private static extern void InternalSetScriptingPtr(
            uint providerId, AudioSampleProvider provider);

        [NativeMethod(IsThreadSafe = true)]
        internal static extern bool InternalIsValid(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern uint InternalGetMaxSampleFrameCount(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern uint InternalGetAvailableSampleFrameCount(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern uint InternalGetFreeSampleFrameCount(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern uint InternalGetFreeSampleFrameCountLowThreshold(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern void InternalSetFreeSampleFrameCountLowThreshold(
            uint providerId, uint sampleFrameCount);

        [NativeMethod(IsThreadSafe = true)]
        private static extern bool InternalGetEnableSampleFramesAvailableEvents(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern void InternalSetEnableSampleFramesAvailableEvents(
            uint providerId, bool enable);

        private static extern void InternalSetSampleFramesAvailableNativeHandler(
            uint providerId, IntPtr handler, IntPtr userData);

        private static extern void InternalClearSampleFramesAvailableNativeHandler(uint providerId);

        private static extern void InternalSetSampleFramesOverflowNativeHandler(
            uint providerId, IntPtr handler, IntPtr userData);

        private static extern void InternalClearSampleFramesOverflowNativeHandler(uint providerId);

        [NativeMethod(IsThreadSafe = true)]
        private static extern bool InternalGetEnableSilencePadding(uint id);

        [NativeMethod(IsThreadSafe = true)]
        private static extern void InternalSetEnableSilencePadding(uint id, bool enabled);

        [NativeMethod(IsThreadSafe = true)]
        private static extern IntPtr InternalGetConsumeSampleFramesNativeFunctionPtr();

        [NativeMethod(IsThreadSafe = true)]
        private static extern UInt32 InternalQueueSampleFrames(
            uint id, IntPtr interleavedSampleFrames, uint sampleFrameCount);
    }
}
